---
title: 'Ecology Workshop: Project Proposal'
author: "Tommy Shannon"
date: "1/10/2020"
output:
  html_document: default
  pdf_document: default
---


I intend to analyze a periphyton dataset from the Everglades CERP sites to understand synchronicity of change in species assemblage with respect to geographic distance over a 13-year period; for sites that exhibit synchronous patterns, I plan to look for explanatory variables such as distance between sites and environmental drivers including phosphorus and chloride.  Ultimately, my hope is to use a similar dataset to test for the presence of chemical intrusion such as saltwater and fertilizer into the same system, but for the purposes of this project my goal is more simply to understand the geotemporal patterns of algal community dynamics and correlate them with similar chemical changes.

I hypothesize that synchronous algal assemblage dynamics will be found among sites, but that intra-site autocorrelation may not be apparent. I additionally hypothesize that those synchrony dynamics will negatively correlate with both geographic and environmental distance between sites, but that those two distance measurements will not strongly correlate with each other.

The dataset I'm working with is one of species-level diatom enumeration alongside data on chemical, physical, and biological properties at each of the sites sampled. The data is sampled from 150 sites within the Florida Everglades CERP area, collected from 2006-2018 with funding from the Army Corps of Engineers. Sites were sampled once per year at a random specific location within a larger 500m^2 quadrant. I have some concern that the temporal resolution may be too coarse to see assemblage patterns which may be present, but the once-yearly sampling will allow me to possibly see longer-scale patterns and trends over the course of the system's water restoration process.
 
Part of my hope for this class is to learn how to best analyze and perform statistical analysis on geotemporally rich datasets like this one.  My plan is to perform matrix regression analyses for beta diversity vs. geographic or environmental distance, but I am eager to better understand what this entails and find out if there are better ways of approaching this data.  The course modules on timeseries analysis and species distribution modeling seem incredibly relevant to my dataset, and so I plan to make the most of them. 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

